// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK0S-ZQxUrUprSdBelEgZqQqp6Gl2zQ3k',
    appId: '1:986130466451:web:93d3f73792d0840c522f66',
    messagingSenderId: '986130466451',
    projectId: 'cci-stat-tracking',
    authDomain: 'cci-stat-tracking.firebaseapp.com',
    storageBucket: 'cci-stat-tracking.appspot.com',
    measurementId: 'G-2L46TTP56L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHHszwr1Sum2Gj4Nz516huzvK9pRckPZM',
    appId: '1:986130466451:android:8589b614261018e7522f66',
    messagingSenderId: '986130466451',
    projectId: 'cci-stat-tracking',
    storageBucket: 'cci-stat-tracking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2MKIihUsek7SS-4gr3SBkUm_9h2McvPY',
    appId: '1:986130466451:ios:4f74ca7af0cf8483522f66',
    messagingSenderId: '986130466451',
    projectId: 'cci-stat-tracking',
    storageBucket: 'cci-stat-tracking.appspot.com',
    iosBundleId: 'com.example.cciStatTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2MKIihUsek7SS-4gr3SBkUm_9h2McvPY',
    appId: '1:986130466451:ios:7d0af338844ae52d522f66',
    messagingSenderId: '986130466451',
    projectId: 'cci-stat-tracking',
    storageBucket: 'cci-stat-tracking.appspot.com',
    iosBundleId: 'com.example.cciStatTracker.RunnerTests',
  );
}
